name: Update README with Recent Activity

on:
  schedule:
<<<<<<< HEAD
    - cron: "*/30 * * * *"
=======
    - cron: "*/30 * * * *" # Update every 30 minutes
>>>>>>> 63a433393ba2551b4354e88a93e03606e42fcba8
  workflow_dispatch:

jobs:
  build:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GitHub Activity Readme
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
